# Generated by Django 5.0.2 on 2024-09-01 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=256, verbose_name='Тема поста')),
                ('content', models.CharField(max_length=4000, verbose_name='Тест поста')),
                ('number_likes', models.IntegerField(verbose_name='Колличество лайков')),
                ('date_publish', models.DateField(auto_now=True, verbose_name='Дата публикации')),
            ],
        ),
    ]
