# Generated by Django 5.0.2 on 2024-09-01 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.CharField(max_length=4000, verbose_name='Текст поста'),
        ),
        migrations.AlterField(
            model_name='post',
            name='number_likes',
            field=models.IntegerField(blank=True, default=0, verbose_name='Лайки'),
        ),
    ]
