# Generated by Django 4.0.2 on 2024-09-02 01:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_alter_post_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(max_length=4000, verbose_name='Текст поста'),
        ),
    ]
