# Generated by Django 4.0.2 on 2024-09-02 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='date_publish',
            field=models.DateField(auto_now_add=True, verbose_name='Дата публикации'),
        ),
    ]
